In [ ]:
TIME = 1000               # number of iterations


def main():
    n = int(input("Enter number of coffee chains: "))
    while not 25 > n > 0:       # error checking
        print("Should be below 25")
        n = int(input("Enter number of coffee chains: "))

    # Taking input from user about the chains and their shift
    print("Enter market share of each coffee chain(sum of share shoud be 1")
    mShare = [float(input()) for i in range(n)]
    shiftRate = []
    for i in range(n):
        print("Enter toShift chain for chain(" + str(i + 1) + "): ", end="")
        temp1 = int(input()) - 1
        print("Enter the shift value to that chain: ", end=" ")
        temp2 = float(input())
        shiftRate.append([temp1, temp2])

    # iterations so that market share changes as per specified manner
    # updation of the market shares should be done simultaneously
    for day in range(TIME):
        newShare = mShare[:]                    # copy of market share
        shift = [0]*n                           # amount to be shifted array
        for chain in range(n):                  # loop per chain
            temp1 = shiftRate[chain][1]         # storing shift value
            temp2 = newShare[chain] - temp1     # storing share value
            if temp2 < 0:                       # check if share is negative
                temp2 = 0                       # put share as 0
                temp1 = newShare[chain]         # store shift as its current market value
            newShare[chain] = round(temp2,1)
            shift[shiftRate[chain][0]] = temp1  # storing shift value
        mShare =[newShare[i]+shift[i] for i in range(n)]    # updating the new market share

    print("\n")
    print("Market share after " + str(TIME) + " days is:", end="")
    print(mShare)

    
#### stupid solution!!!
########################

In [2]:
import numpy as np


In [4]:
a=np.array([0.4,0.6])
b=np.array([[0.8,0.2],[0.1,0.9]])

In [5]:
b

array([[0.8, 0.2],
       [0.1, 0.9]])

In [6]:
np.dot(a,b)

array([0.38, 0.62])

In [7]:
for i in range(1000):
    a = np.dot(a,b)
a

array([0.33333333, 0.66666667])

In [8]:
a1 = [0.4,0.6]
b2=[[0.8,0.2],[0.1,0.9]]

In [9]:
np.dot(a,b)

array([0.33333333, 0.66666667])