In [1]:
import numpy as np

In [62]:
arr=np.array([[5,5,5,5,5],[5,1,5,5,5],[5,5,5,4,5],[5,5,4,2,3],[0,5,5,3,4]])

In [63]:
print(arr)

[[5 5 5 5 5]
 [5 1 5 5 5]
 [5 5 5 4 5]
 [5 5 4 2 3]
 [0 5 5 3 4]]


5

In [60]:
# find local minima of a 2D array
def check_min(arr,i,j,n):
    top = arr[i-1,j] if i-1>=0 else np.iinfo(np.int32).max
    bot = arr[i+1,j] if i+1<n else np.iinfo(np.int32).max
    left = arr[i,j-1] if j-1 >=0 else np.iinfo(np.int32).max
    right = arr[i,j+1] if j+1<n else np.iinfo(np.int32).max
    tmp = arr[i,j]
    if tmp < min(top, bot,left,right):
        return True
    else:
        return False


def minima(arr):
    n = arr.shape[0]
    res = []
    for i in range(n):
        for j in range(n):
            if check_min(arr,i,j,n):
                res.append(arr[i,j])
    res.sort()
    return res[0:3]



In [61]:
minima(arr)

[0, 1, 2]